### ISSUE TITLE
Canvas stretches over entire window since Spotify version 1.2.34.783

### ISSUE THREAD

**Issue by Konsl** [Konsl/spicetify-ncs-visualizer#21]
```
Spotify for Windows (64 bit)
1.2.34.783.g923721d9
Spicetify v2.36.2
xpui_2024-03-22_1711126575406_923721d
cef_122.1.13+gde5b724+chromium-122.0.6261.130
Runtime: Chrome
```

app fills the entire screen instead of just center area

![screenshot](https://github.com/Konsl/spicetify-ncs-visualizer/assets/82901383/dde7c82a-3629-4f92-b680-332119f11333)

**Comment by Konsl** [comment]
Reverting c98f1d7 would fix this, but this would break compatibility with Comfy theme, see #3

**Comment by Konsl** [comment]
I've decided to revert the previous change. Use this CSS snippet to make the visualizer visible when using Comfy theme.
```CSS
.ncs-visualizer-container {
  height: calc(100vh - max(var(--comfy-topbar-height, 40px), 8px) - 100px);
  margin-top: -64px;
}
```
