### ISSUE TITLE
Visualizer too very small size problem!

### ISSUE THREAD

**Issue by MYKGeZazZ** [Konsl/spicetify-ncs-visualizer#29]
I installed the visualizer and faced its very small size..I even installed it again and faced the same problem..how to fix?
![Screenshot 2024-07-04 100342](https://github.com/Konsl/spicetify-ncs-visualizer/assets/162330107/2acb638e-8204-43b3-992d-9960cf0adffc)

**Comment by Konsl** [comment]
Which theme is this?

**Comment by txhno** [comment]
have the same issue, theme: `catppuccin-mocha`

**Comment by ArchknightO-O** [comment]
Same issue here. Theme: `Comfy`

**Comment by Konsl** [comment]
I am unable to reproduce this specific issue with Catpuccin. For Comfy, use [this snippet](https://github.com/Konsl/spicetify-visualizer/issues/21#issuecomment-2050515422) (also linked in the main readme).

**Comment by jnobbe** [comment]
This fixed the issue for me @Konsl.

**Comment by DMCK96** [comment]
This issue is still happening for me with comfy and using that css-snippet.

**Comment by EDM115** [comment]
one snipped who fixed it for me (and also fixes other tabs like lyrics) : 
```css
.Root__main-view > div {
    height: inherit;
    margin: inherit;
    padding-bottom: 30px; /* Relative to your screen resolution and zoom level */
}
```
i'm using [Bloom](https://github.com/nimsandu/spicetify-bloom) if that matters
